# Generated by Django 5.2.5 on 2025-09-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('versao', models.CharField(max_length=20)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
