# Generated by Django 5.2.5 on 2025-09-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0002_cliente_alter_norma_data_publicacao_normacliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norma',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='versao',
        ),
        migrations.AddField(
            model_name='norma',
            name='formato',
            field=models.CharField(choices=[('digital', 'Digital'), ('impresso', 'Impresso')], default='digital', max_length=20),
        ),
        migrations.AddField(
            model_name='norma',
            name='idioma',
            field=models.CharField(choices=[('ingles', 'Inglês'), ('portugues', 'Português')], default='portugues', max_length=20),
        ),
        migrations.AddField(
            model_name='norma',
            name='norma',
            field=models.CharField(default='N/A', help_text='O número ou código da norma, ex: GMW3059', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='norma',
            name='organizacao',
            field=models.CharField(default='N/A', help_text='Ex: ABNT, ISO, GM', max_length=200),
        ),
        migrations.AddField(
            model_name='norma',
            name='revisao_atual',
            field=models.CharField(default='N/A', help_text='A versão da revisão atual, ex: 06/06/2000', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(help_text='Somente números', max_length=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(help_text='Somente números', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(help_text='Ex: Avenida Lauro Gomes, 5901', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Somente números (incluir DDD)', max_length=15),
        ),
        migrations.AlterField(
            model_name='norma',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='RevisaoSecundariaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_revisao', models.CharField(choices=[('errata', 'Errata'), ('reafirmacao', 'Reafirmação'), ('ammendment', 'Ammendment')], max_length=50)),
                ('data', models.DateField()),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_normas.norma')),
            ],
        ),
    ]
