# Generated by Django 5.2.5 on 2025-09-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0005_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(help_text='Somente numeros', max_length=8),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(help_text='Somente numeros', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Somente numeros (incluir DDD)', max_length=11),
        ),
    ]
