# Generated by Django 5.2.5 on 2025-09-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0006_alter_cliente_cep_alter_cliente_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='revisao_atual',
            field=models.DateField(help_text='A versão da revisão atual, ex: 06/06/2000'),
        ),
    ]
