# Generated by Django 5.2.5 on 2025-09-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0007_alter_norma_revisao_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pais',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vigencia_contratual_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vigencia_contratual_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
