# Generated by Django 5.2.5 on 2025-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0009_perfilusuario_normas_favoritas'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observacoes internas sobre a norma.', null=True),
        ),
    ]
