# Generated by Django 5.2.5 on 2025-09-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0010_norma_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observacoes internas sobre a norma.', max_length=200, null=True),
        ),
    ]
