# Generated by Django 5.2.6 on 2025-09-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0013_auditoria_centrodecusto_certificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='is_admin_cliente',
            new_name='pode_gerenciar_auditorias',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_gerenciar_centros_de_custo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_gerenciar_certificacoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_gerenciar_comentarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_gerenciar_favoritos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_gerenciar_precos',
            field=models.BooleanField(default=False),
        ),
    ]
