# Generated by Django 5.2.6 on 2025-09-29 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0014_rename_is_admin_cliente_perfilusuario_pode_gerenciar_auditorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='gestao_normas.comentario'),
        ),
    ]
