# Generated by Django 5.2.5 on 2025-09-08 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(help_text='Nome da empresa.', max_length=200)),
                ('cnpj', models.CharField(help_text='Formato: 99.999.999/9999-99', max_length=18, unique=True)),
                ('dominio', models.CharField(help_text='Ex: google.com', max_length=100)),
                ('endereco', models.CharField(help_text='Rua e número.', max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=50)),
                ('cep', models.CharField(help_text='Formato: 99999-999', max_length=9)),
                ('telefone', models.CharField(help_text='Formato: (99) 99999-9999', max_length=15)),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='norma',
            name='data_publicacao',
            field=models.DateField(help_text='Data oficial de publicação da norma.'),
        ),
        migrations.CreateModel(
            name='NormaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_revisao_cliente', models.DateField(help_text='Data da última revisão desta norma no cliente.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_normas.cliente')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_normas.norma')),
            ],
            options={
                'unique_together': {('cliente', 'norma')},
            },
        ),
        migrations.AddField(
            model_name='norma',
            name='clientes',
            field=models.ManyToManyField(through='gestao_normas.NormaCliente', to='gestao_normas.cliente'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_normas.cliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
