# Generated by Django 5.2.5 on 2025-09-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0003_remove_norma_codigo_remove_norma_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='is_admin_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
