# Generated by Django 5.2.5 on 2025-09-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_normas', '0008_remove_cliente_pais_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='normas_favoritas',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='gestao_normas.norma'),
        ),
    ]
